### ISSUE TITLE
ImportError: No module named keras_contrib.layers.normalization.instancenormalization

### ISSUE THREAD

**Issue by avaseghi** [bendangnuksung/Image-OutPainting#8]
No matter what I do, every time I run outpaint.ipynb I get an error saying there's no keras_contrib module even though I see it listed using pip freeze. I looked at the issues on the keras-contrib Github page and people who have run into the same issue said they installed Python 3.7 but that hasn't been released yet. Do you have any idea why this might be happening and how to resolve it??

**Comment by bendangnuksung** [comment]
@avaseghi  Currently using Python 3.6 and installed keras-contrib==2.0.8,  there seems to be no problem. Can you please specify your Python and Keras_contrib version.

**Comment by bendangnuksung** [comment]
Closing as there was no follow up.
