### ISSUE TITLE
how should i test?

### ISSUE THREAD

**Issue by zhangbaijin** [bendangnuksung/Image-OutPainting#9]
i downloaded your trained model .but i didn't see test.py , how should i test your model

**Comment by bendangnuksung** [comment]
1. Prepare data if you have not, prepare using `sh prepare_data.sh`
2. Extract and move the download files to `checkpoint/` directory.
3. Open jupyter notebook and run `outpaint.ipynb`

**Comment by bendangnuksung** [comment]
There is also a section inside `outpaint.ipynb` called Test from URL where you can just provide an image URL and test the result.

**Comment by zhangbaijin** [comment]
ok,thanks a lot!
